apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xoexhwdao-python 
  janus-idp.io/tekton: xoexhwdao-python
  backstage.io/kubernetes-id: xoexhwdao-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xoexhwdao-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  